name: 'Setup Environment'
description: 'Shared action to setup Node.js and pnpm'

runs:
  using: 'composite'
  steps:
    - name: Set up pnpm and Node.js
      uses: pnpm/setup@v1
      with:
        runtime: node@24
        cache: true
