name: PR Check

on:
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Env
        uses: ./.github/actions/setup-env

      - name: Lint
        run: pnpm run lint

      - name: Format Check
        run: pnpm run format:check

      - name: Test
        run: pnpm run test

      - name: Build
        run: pnpm run build
