name: Release

on:
  push:
    branches: [main]

jobs:
  build-and-verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Env
        uses: ./.github/actions/setup-env

      - name: Test & Build
        run: |
          pnpm run test
          pnpm run build

      # - name: Publish to npm
      #   run: pnpm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
