name: Release

on:
  push:
    branches:
      - main
    paths:
      - '.changeset/*.md'

  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Env
        uses: ./.github/actions/setup-env

      - name: Create Release PR
        uses: changesets/action@v1
        with:
          version: pnpm exec changeset version
          title: 'chore: release package'
          commit: 'chore: release package'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
